### ISSUE TITLE
Cargo install bootimage fails

### ISSUE THREAD

**Issue by therishidesai** [rust-osdev/bootimage#12]
When I try to cargo install bootimage, I get the following error.
```
error[E0425]: cannot find function `read_to_string` in module `fs`
  --> src/test.rs:66:34
   |
66 |                 let output = fs::read_to_string(&output_file)
   |                                  ^^^^^^^^^^^^^^ did you mean `read_string`?

error: aborting due to previous error

error: failed to compile `bootimage v0.4.3`, intermediate artifacts can be found at `/tmp/cargo-install.bb6pN4pqkVxR`
```

**Comment by apache8080** [comment]
When I did rustup update stable it ran fine. I guess the current nightly build had issues.

**Comment by phil-opp** [comment]
Seems like you just used an old compiler: The `read_string` function was renamed to `read_to_string` in https://github.com/rust-lang/rust/pull/49522 and was stabilized in [1.26](https://blog.rust-lang.org/2018/05/10/Rust-1.26.html#library-stabilizations).
