### ISSUE TITLE
bootimage 0.5 broke intermezzos

### ISSUE THREAD

**Issue by steveklabnik** [rust-osdev/bootimage#17]
0.3 and i'm guessing 0.4 worked, but now

```
> bootimage build
Building kernel
    Finished dev [unoptimized + debuginfo] target(s) in 0.05s
Error: Failed to build bootloader
```

Anything more I can do to help figure out what's wrong?

**Comment by phil-opp** [comment]
Oh yes, there were some breaking changes: https://github.com/rust-osdev/bootimage/pull/16

I thought that I updated the error message to link this pull request and the migration guide, but it seems like I missed something. I try to look into it. Sorry for the breakage!

**Comment by phil-opp** [comment]
Seems like I'm hitting https://github.com/rust-lang-nursery/failure/issues/182. Instead of the real error message only the `context` argument is printed.

**Comment by phil-opp** [comment]
For an example how version 0.5.0 is used, see https://os.phil-opp.com/minimal-rust-kernel/#creating-a-bootimage

**Comment by steveklabnik** [comment]
Thanks a ton!
