### ISSUE TITLE
Package always has len 0

### ISSUE THREAD

**Issue by chronium** [rust-osdev/bootimage#23]
I am trying to provide a package to the kernel, but somehow, anything I provide ends up with a length of 0. Reading the code, that should not happen, but strangely enough, it does. I tried with multiple file types even though it should not be a problem, but still the same result.

**Comment by phil-opp** [comment]
cc @lachlansneff, who implemented this feature

**Comment by phil-opp** [comment]
I did some investigation and it seems like the implementation is not finished yet: The bootloader crate was not updated yet to support loading a package. It seems like @lachlansneff uses a custom bootloader with that functionality for nebulet: https://github.com/nebulet/nebulet/blob/master/Cargo.toml#L61

**Comment by phil-opp** [comment]
Is there a reason why you can't just use [`include_bytes`](https://doc.rust-lang.org/std/macro.include_bytes.html)?

**Comment by chronium** [comment]
I was actually planning to use include_bytes as it does a very similar thing. Until the implementation is complete, include_bytes will have to do. Thank you for looking into it.

**Comment by phil-opp** [comment]
Alternatively you can include it in your linker script if you want to control placement and alignment.
