### ISSUE TITLE
Refactor

### ISSUE THREAD

**Issue by lachlansneff** [rust-osdev/bootimage#3]
Bootimage should be refactored to allow it to be expanded more easily.

- [ ] Move functionality to separate files.
- [ ] Add the ability to parse a Boot.toml instead of cmd-line arguments.
  - [ ] Pass features to bootloader
  - [ ] Custom paths/git-repos to download/build bootloader from.
- [ ] Sensible defaults (it should work without any configuration)

**Comment by phil-opp** [comment]
Sounds good!
