### ISSUE TITLE
Document non default bootloader

### ISSUE THREAD

**Issue by fdb-hiroshima** [rust-osdev/bootimage#4]
Currently if you try to compile a boot-loader by yourself with --build-bootloader, you have to delete `target/x86_64-unknown-blog_os/{debug,release}/bootloader.bin` (if you already ran the tool, using precompiled boot-loader or by compiling yourself), otherwise it will keep using old bootloader.
Moreover if you want to use an other git repository than the default, you have to delete `target/x86_64-unknown-blog_os/{debug,release}/bootloader/` if "bootloader" was the name of the old repository. If you don't the tool will keep using the old repository. Not that this issue apply even if new repository is called differently, but does not if old repository was anything different than "bootloader".
An easy fix is to just run `cargo clean`, but this should be documented somewhere

**Comment by phil-opp** [comment]
Thanks for reporting this! I absolutely agree that the situation needs to improve. At the moment, the tool is just an early prototype, so we still have to work on both the implementation and documentation.
