### ISSUE TITLE
Feature Request: Multiple Modules

### ISSUE THREAD

**Issue by wsKilljoy** [rust-osdev/bootimage#50]
Hi - Is support for multiple modules (such as an initrd) planned? Thanks!

**Comment by phil-opp** [comment]
I'm not sure yet. I plan to start working with [`include_bytes`](https://doc.rust-lang.org/core/macro.include_bytes.html) and see how far I can get.

**Comment by phil-opp** [comment]
I'm of course open to proposals and pull requests, I just won't implement it myself until I need it.

**Comment by wsKilljoy** [comment]
Fair enough. I'm currently just writing the contents of a generated binary to a `const &[u8]`. Although it's a pretty hacky solution, it works for now.

**Comment by phil-opp** [comment]
>  I'm currently just writing the contents of a generated binary to a `const &[u8]`

That's exactly what `include_bytes` does.

>  Although it's a pretty hacky solution, it works for now.

Yeah, I agree that it's not optimal, but at least it works :).
