### ISSUE TITLE
bootloader cannot find crate core

### ISSUE THREAD

**Issue by Lord-Remington-the-3rd** [rust-osdev/bootimage#60]
error[E0461]: couldn't find crate `core` with expected target triple x86_64-bootloader-8493042128464191786
  |
  = note: the following crate versions were found:
          crate `core`, target triple x86_64-bootloader-14747452034751789700: /home/tinyman/Documents/kern/target/bootimage/bootloader/bootloader-sysroot/lib/rustlib/x86_64-bootloader/lib/libcore-6c95d5ee8df52f8b.rmeta
          crate `core`, target triple x86_64-bootloader-14747452034751789700: /home/tinyman/Documents/kern/target/bootimage/bootloader/bootloader-sysroot/lib/rustlib/x86_64-bootloader/lib/libcore-6c95d5ee8df52f8b.rlib

error: aborting due to previous error

####################################################################################################
I dont know why this is happening tbh... 

[Cargo.toml.txt](https://github.com/rust-osdev/bootimage/files/4822460/Cargo.toml.txt)
[x64_target.json.txt](https://github.com/rust-osdev/bootimage/files/4822463/x64_target.json.txt)

NIGHTLY VERSION: 1.46
RUST EDITION: 2018

BOOTIMAGE VERSION: 0.9.4 (tried that all the way down to 0.9.2

**Comment by phil-opp** [comment]
Could you try running `cargo clean` and then trying it again?

**Comment by Lord-Remington-the-3rd** [comment]
Sweet, it worked. Thank your sir! And thank you for this wonderful program and your wonderful tutorial!

**Comment by phil-opp** [comment]
You're welcome!
