### ISSUE TITLE
Can't Install bootimage with cargo install bootimage

### ISSUE THREAD

**Issue by VectorAnimator** [rust-osdev/bootimage#88]
Anytime I try to install bootimage I get this error:
![image](https://user-images.githubusercontent.com/73546596/197352033-91af5ad7-d719-490b-bdf2-13590c7eda3b.png)
Any Help will be appreciated.

**Comment by VectorAnimator** [comment]
I solved the issue, it seems I added an underscore instead of dash in "compiler-builtins-mem"

**Comment by phil-opp** [comment]
Thanks for the update, good to hear that you figured out the issue.

Where did you create your `.cargo/config.toml` file? I recommend to set the build-std features only in a project-level `.cargo/config.toml`, not in your global one.

**Comment by VectorAnimator** [comment]
Thanks for the tip!
